language: generic

sudo: required

services:
  - docker

branches:
  only:
    - master

before_install:
  - docker build -f Dockerfile.dev -t unnicognizant/docker-react-sample .

script:
  - docker run -e CI=true unnicognizant/docker-react-sample npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-476417356674"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

