sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:
  - docker build -f Dockerfile.dev -t unnicognizant/docker-react-sample .

script:
  - docker run -e CI=true unnicognizant/docker-react-sample npm run test -- --coverage
